export enum NodeType {
  NodeDocument = 0,
  NodeParagraph,
  NodeHeading,
  NodeHeadingC8hMarker,
  NodeThematicBreak,
  NodeBlockquote,
  NodeBlockquoteMarker,
  NodeList,
  NodeListItem,
  NodeHTMLBlock,
  NodeInlineHTML,
  NodeCodeBlock,
  NodeCodeBlockFenceOpenMarker,
  NodeCodeBlockFenceCloseMarker,
  NodeCodeBlockFenceInfoMarker,
  NodeCodeBlockCode,
  NodeText,
  NodeEmphasis,
  NodeEmA6kOpenMarker,
  NodeEmA6kCloseMarker,
  NodeEmU8eOpenMarker,
  NodeEmU8eCloseMarker,
  NodeStrong,
  NodeStrongA6kOpenMarker,
  NodeStrongA6kCloseMarker,
  NodeStrongU8eOpenMarker,
  NodeStrongU8eCloseMarker,
  NodeCodeSpan,
  NodeCodeSpanOpenMarker,
  NodeCodeSpanContent,
  NodeCodeSpanCloseMarker,
  NodeHardBreak,
  NodeSoftBreak,
  NodeLink,
  NodeImage,
  NodeBang,
  NodeOpenBracket,
  NodeCloseBracket,
  NodeOpenParen,
  NodeCloseParen,
  NodeLinkText,
  NodeLinkDest,
  NodeLinkTitle,
  NodeLinkSpace,
  NodeHTMLEntity,
  NodeLinkRefDefBlock,
  NodeLinkRefDef,
  NodeLess,
  NodeGreater,
  NodeTaskListItemMarker = 100,
  NodeStrikethrough,
  NodeStrikethrough1OpenMarker,
  NodeStrikethrough1CloseMarker,
  NodeStrikethrough2OpenMarker,
  NodeStrikethrough2CloseMarker,
  NodeTable,
  NodeTableHead,
  NodeTableRow,
  NodeTableCell,
  NodeEmoji = 200,
  NodeEmojiUnicode,
  NodeEmojiImg,
  NodeEmojiAlias,
  NodeMathBlock = 300,
  NodeMathBlockOpenMarker,
  NodeMathBlockContent,
  NodeMathBlockCloseMarker,
  NodeInlineMath,
  NodeInlineMathOpenMarker,
  NodeInlineMathContent,
  NodeInlineMathCloseMarker,
  NodeBackslash = 400,
  NodeBackslashContent,
  NodeVditorCaret = 405,
  NodeFootnotesDefBlock = 410,
  NodeFootnotesDef,
  NodeFootnotesRef,
  NodeToC = 415,
  NodeHeadingID = 420,
  NodeYamlFrontMatter = 425,
  NodeYamlFrontMatterOpenMarker,
  NodeYamlFrontMatterContent,
  NodeYamlFrontMatterCloseMarker,
  NodeBlockRef = 430,
  NodeBlockRefID,
  NodeBlockRefSpace,
  NodeBlockRefText,
  NodeBlockRefDynamicText,
  NodeMark = 450,
  NodeMark1OpenMarker,
  NodeMark1CloseMarker,
  NodeMark2OpenMarker,
  NodeMark2CloseMarker,
  NodeKramdownBlockIAL = 455,
  NodeKramdownSpanIAL,
  NodeTag = 460,
  NodeTagOpenMarker,
  NodeTagCloseMarker,
  NodeBlockQueryEmbed = 465,
  NodeOpenBrace,
  NodeCloseBrace,
  NodeBlockQueryEmbedScript,
  NodeSuperBlock = 475,
  NodeSuperBlockOpenMarker,
  NodeSuperBlockLayoutMarker,
  NodeSuperBlockCloseMarker,
  NodeSup = 485,
  NodeSupOpenMarker,
  NodeSupCloseMarker,
  NodeSub = 490,
  NodeSubOpenMarker,
  NodeSubCloseMarker,
  NodeGitConflict = 495,
  NodeGitConflictOpenMarker,
  NodeGitConflictContent,
  NodeGitConflictCloseMarker,
  NodeIFrame = 500,
  NodeAudio = 505,
  NodeVideo = 510,
  NodeKbd = 515,
  NodeKbdOpenMarker,
  NodeKbdCloseMarker,
  NodeUnderline = 520,
  NodeUnderlineOpenMarker,
  NodeUnderlineCloseMarker,
  NodeBr = 525,
  NodeTextMark = 530,
  NodeWidget = 535,
  NodeFileAnnotationRef = 540,
  NodeFileAnnotationRefID,
  NodeFileAnnotationRefSpace,
  NodeFileAnnotationRefText,
  NodeAttributeView = 550,
  NodeCustomBlock = 560,
  NodeHTMLTag = 570,
  NodeHTMLTagOpen,
  NodeHTMLTagClose,
  NodeTypeMaxVal = 1024,
}

export const NodeTypeMap: { [key: number]: string } = {
  [NodeType.NodeDocument]: "NodeDocument",
  [NodeType.NodeParagraph]: "NodeParagraph",
  [NodeType.NodeHeading]: "NodeHeading",
  [NodeType.NodeHeadingC8hMarker]: "NodeHeadingC8hMarker",
  [NodeType.NodeThematicBreak]: "NodeThematicBreak",
  [NodeType.NodeBlockquote]: "NodeBlockquote",
  [NodeType.NodeBlockquoteMarker]: "NodeBlockquoteMarker",
  [NodeType.NodeList]: "NodeList",
  [NodeType.NodeListItem]: "NodeListItem",
  [NodeType.NodeHTMLBlock]: "NodeHTMLBlock",
  [NodeType.NodeInlineHTML]: "NodeInlineHTML",
  [NodeType.NodeCodeBlock]: "NodeCodeBlock",
  [NodeType.NodeCodeBlockFenceOpenMarker]: "NodeCodeBlockFenceOpenMarker",
  [NodeType.NodeCodeBlockFenceCloseMarker]: "NodeCodeBlockFenceCloseMarker",
  [NodeType.NodeCodeBlockFenceInfoMarker]: "NodeCodeBlockFenceInfoMarker",
  [NodeType.NodeCodeBlockCode]: "NodeCodeBlockCode",
  [NodeType.NodeText]: "NodeText",
  [NodeType.NodeEmphasis]: "NodeEmphasis",
  [NodeType.NodeEmA6kOpenMarker]: "NodeEmA6kOpenMarker",
  [NodeType.NodeEmA6kCloseMarker]: "NodeEmA6kCloseMarker",
  [NodeType.NodeEmU8eOpenMarker]: "NodeEmU8eOpenMarker",
  [NodeType.NodeEmU8eCloseMarker]: "NodeEmU8eCloseMarker",
  [NodeType.NodeStrong]: "NodeStrong",
  [NodeType.NodeStrongA6kOpenMarker]: "NodeStrongA6kOpenMarker",
  [NodeType.NodeStrongA6kCloseMarker]: "NodeStrongA6kCloseMarker",
  [NodeType.NodeStrongU8eOpenMarker]: "NodeStrongU8eOpenMarker",
  [NodeType.NodeStrongU8eCloseMarker]: "NodeStrongU8eCloseMarker",
  [NodeType.NodeCodeSpan]: "NodeCodeSpan",
  [NodeType.NodeCodeSpanOpenMarker]: "NodeCodeSpanOpenMarker",
  [NodeType.NodeCodeSpanContent]: "NodeCodeSpanContent",
  [NodeType.NodeCodeSpanCloseMarker]: "NodeCodeSpanCloseMarker",
  [NodeType.NodeHardBreak]: "NodeHardBreak",
  [NodeType.NodeSoftBreak]: "NodeSoftBreak",
  [NodeType.NodeLink]: "NodeLink",
  [NodeType.NodeImage]: "NodeImage",
  [NodeType.NodeBang]: "NodeBang",
  [NodeType.NodeOpenBracket]: "NodeOpenBracket",
  [NodeType.NodeCloseBracket]: "NodeCloseBracket",
  [NodeType.NodeOpenParen]: "NodeOpenParen",
  [NodeType.NodeCloseParen]: "NodeCloseParen",
  [NodeType.NodeLinkText]: "NodeLinkText",
  [NodeType.NodeLinkDest]: "NodeLinkDest",
  [NodeType.NodeLinkTitle]: "NodeLinkTitle",
  [NodeType.NodeLinkSpace]: "NodeLinkSpace",
  [NodeType.NodeHTMLEntity]: "NodeHTMLEntity",
  [NodeType.NodeLinkRefDefBlock]: "NodeLinkRefDefBlock",
  [NodeType.NodeLinkRefDef]: "NodeLinkRefDef",
  [NodeType.NodeLess]: "NodeLess",
  [NodeType.NodeGreater]: "NodeGreater",
  [NodeType.NodeTaskListItemMarker]: "NodeTaskListItemMarker",
  [NodeType.NodeStrikethrough]: "NodeStrikethrough",
  [NodeType.NodeStrikethrough1OpenMarker]: "NodeStrikethrough1OpenMarker",
  [NodeType.NodeStrikethrough1CloseMarker]: "NodeStrikethrough1CloseMarker",
  [NodeType.NodeStrikethrough2OpenMarker]: "NodeStrikethrough2OpenMarker",
  [NodeType.NodeStrikethrough2CloseMarker]: "NodeStrikethrough2CloseMarker",
  [NodeType.NodeTable]: "NodeTable",
  [NodeType.NodeTableHead]: "NodeTableHead",
  [NodeType.NodeTableRow]: "NodeTableRow",
  [NodeType.NodeTableCell]: "NodeTableCell",
  [NodeType.NodeEmoji]: "NodeEmoji",
  [NodeType.NodeEmojiUnicode]: "NodeEmojiUnicode",
  [NodeType.NodeEmojiImg]: "NodeEmojiImg",
  [NodeType.NodeEmojiAlias]: "NodeEmojiAlias",
  [NodeType.NodeMathBlock]: "NodeMathBlock",
  [NodeType.NodeMathBlockOpenMarker]: "NodeMathBlockOpenMarker",
  [NodeType.NodeMathBlockContent]: "NodeMathBlockContent",
  [NodeType.NodeMathBlockCloseMarker]: "NodeMathBlockCloseMarker",
  [NodeType.NodeInlineMath]: "NodeInlineMath",
  [NodeType.NodeInlineMathOpenMarker]: "NodeInlineMathOpenMarker",
  [NodeType.NodeInlineMathContent]: "NodeInlineMathContent",
  [NodeType.NodeInlineMathCloseMarker]: "NodeInlineMathCloseMarker",
  [NodeType.NodeBackslash]: "NodeBackslash",
  [NodeType.NodeBackslashContent]: "NodeBackslashContent",
  [NodeType.NodeVditorCaret]: "NodeVditorCaret",
  [NodeType.NodeFootnotesDefBlock]: "NodeFootnotesDefBlock",
  [NodeType.NodeFootnotesDef]: "NodeFootnotesDef",
  [NodeType.NodeFootnotesRef]: "NodeFootnotesRef",
  [NodeType.NodeToC]: "NodeToC",
  [NodeType.NodeHeadingID]: "NodeHeadingID",
  [NodeType.NodeYamlFrontMatter]: "NodeYamlFrontMatter",
  [NodeType.NodeYamlFrontMatterOpenMarker]: "NodeYamlFrontMatterOpenMarker",
  [NodeType.NodeYamlFrontMatterContent]: "NodeYamlFrontMatterContent",
  [NodeType.NodeYamlFrontMatterCloseMarker]: "NodeYamlFrontMatterCloseMarker",
  [NodeType.NodeBlockRef]: "NodeBlockRef",
  [NodeType.NodeBlockRefID]: "NodeBlockRefID",
  [NodeType.NodeBlockRefSpace]: "NodeBlockRefSpace",
  [NodeType.NodeBlockRefText]: "NodeBlockRefText",
  [NodeType.NodeBlockRefDynamicText]: "NodeBlockRefDynamicText",
  [NodeType.NodeMark]: "NodeMark",
  [NodeType.NodeMark1OpenMarker]: "NodeMark1OpenMarker",
  [NodeType.NodeMark1CloseMarker]: "NodeMark1CloseMarker",
  [NodeType.NodeMark2OpenMarker]: "NodeMark2OpenMarker",
  [NodeType.NodeMark2CloseMarker]: "NodeMark2CloseMarker",
  [NodeType.NodeKramdownBlockIAL]: "NodeKramdownBlockIAL",
  [NodeType.NodeKramdownSpanIAL]: "NodeKramdownSpanIAL",
  [NodeType.NodeTag]: "NodeTag",
  [NodeType.NodeTagOpenMarker]: "NodeTagOpenMarker",
  [NodeType.NodeTagCloseMarker]: "NodeTagCloseMarker",
  [NodeType.NodeBlockQueryEmbed]: "NodeBlockQueryEmbed",
  [NodeType.NodeOpenBrace]: "NodeOpenBrace",
  [NodeType.NodeCloseBrace]: "NodeCloseBrace",
  [NodeType.NodeBlockQueryEmbedScript]: "NodeBlockQueryEmbedScript",
  [NodeType.NodeSuperBlock]: "NodeSuperBlock",
  [NodeType.NodeSuperBlockOpenMarker]: "NodeSuperBlockOpenMarker",
  [NodeType.NodeSuperBlockLayoutMarker]: "NodeSuperBlockLayoutMarker",
  [NodeType.NodeSuperBlockCloseMarker]: "NodeSuperBlockCloseMarker",
  [NodeType.NodeSup]: "NodeSup",
  [NodeType.NodeSupOpenMarker]: "NodeSupOpenMarker",
  [NodeType.NodeSupCloseMarker]: "NodeSupCloseMarker",
  [NodeType.NodeSub]: "NodeSub",
  [NodeType.NodeSubOpenMarker]: "NodeSubOpenMarker",
  [NodeType.NodeSubCloseMarker]: "NodeSubCloseMarker",
  [NodeType.NodeGitConflict]: "NodeGitConflict",
  [NodeType.NodeGitConflictOpenMarker]: "NodeGitConflictOpenMarker",
  [NodeType.NodeGitConflictContent]: "NodeGitConflictContent",
  [NodeType.NodeGitConflictCloseMarker]: "NodeGitConflictCloseMarker",
  [NodeType.NodeIFrame]: "NodeIFrame",
  [NodeType.NodeAudio]: "NodeAudio",
  [NodeType.NodeVideo]: "NodeVideo",
  [NodeType.NodeKbd]: "NodeKbd",
  [NodeType.NodeKbdOpenMarker]: "NodeKbdOpenMarker",
  [NodeType.NodeKbdCloseMarker]: "NodeKbdCloseMarker",
  [NodeType.NodeUnderline]: "NodeUnderline",
  [NodeType.NodeUnderlineOpenMarker]: "NodeUnderlineOpenMarker",
  [NodeType.NodeUnderlineCloseMarker]: "NodeUnderlineCloseMarker",
  [NodeType.NodeBr]: "NodeBr",
  [NodeType.NodeTextMark]: "NodeTextMark",
  [NodeType.NodeWidget]: "NodeWidget",
  [NodeType.NodeFileAnnotationRef]: "NodeFileAnnotationRef",
  [NodeType.NodeFileAnnotationRefID]: "NodeFileAnnotationRefID",
  [NodeType.NodeFileAnnotationRefSpace]: "NodeFileAnnotationRefSpace",
  [NodeType.NodeFileAnnotationRefText]: "NodeFileAnnotationRefText",
  [NodeType.NodeAttributeView]: "NodeAttributeView",
  [NodeType.NodeCustomBlock]: "NodeCustomBlock",
  [NodeType.NodeHTMLTag]: "NodeHTMLTag",
  [NodeType.NodeHTMLTagOpen]: "NodeHTMLTagOpen",
  [NodeType.NodeHTMLTagClose]: "NodeHTMLTagClose",
  [NodeType.NodeTypeMaxVal]: "NodeTypeMaxVal",
};

export function NodeTypeToString(nodeType: NodeType): string {
  return NodeTypeMap[nodeType];
}
